// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// BayDuBiG_mcmc
Rcpp::List BayDuBiG_mcmc(const arma::mat& Y, const Rcpp::List& gene_group_list, const Rcpp::Nullable<Rcpp::NumericMatrix>& XWX, const arma::vec& X_coord, const arma::vec& Y_coord, const arma::sp_mat& weights, int iter, int burn, double a_rho, double b_rho, double a_tau, double b_tau, double a_gamma, double b_gamma, double a_sigma, double b_sigma, bool informative_gamma, double a_gamma_on, double b_gamma_on, double a_gamma_off, double b_gamma_off);
RcppExport SEXP _BayDuBiG_BayDuBiG_mcmc(SEXP YSEXP, SEXP gene_group_listSEXP, SEXP XWXSEXP, SEXP X_coordSEXP, SEXP Y_coordSEXP, SEXP weightsSEXP, SEXP iterSEXP, SEXP burnSEXP, SEXP a_rhoSEXP, SEXP b_rhoSEXP, SEXP a_tauSEXP, SEXP b_tauSEXP, SEXP a_gammaSEXP, SEXP b_gammaSEXP, SEXP a_sigmaSEXP, SEXP b_sigmaSEXP, SEXP informative_gammaSEXP, SEXP a_gamma_onSEXP, SEXP b_gamma_onSEXP, SEXP a_gamma_offSEXP, SEXP b_gamma_offSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type gene_group_list(gene_group_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::NumericMatrix>& >::type XWX(XWXSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type X_coord(X_coordSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y_coord(Y_coordSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< int >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< double >::type a_rho(a_rhoSEXP);
    Rcpp::traits::input_parameter< double >::type b_rho(b_rhoSEXP);
    Rcpp::traits::input_parameter< double >::type a_tau(a_tauSEXP);
    Rcpp::traits::input_parameter< double >::type b_tau(b_tauSEXP);
    Rcpp::traits::input_parameter< double >::type a_gamma(a_gammaSEXP);
    Rcpp::traits::input_parameter< double >::type b_gamma(b_gammaSEXP);
    Rcpp::traits::input_parameter< double >::type a_sigma(a_sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type b_sigma(b_sigmaSEXP);
    Rcpp::traits::input_parameter< bool >::type informative_gamma(informative_gammaSEXP);
    Rcpp::traits::input_parameter< double >::type a_gamma_on(a_gamma_onSEXP);
    Rcpp::traits::input_parameter< double >::type b_gamma_on(b_gamma_onSEXP);
    Rcpp::traits::input_parameter< double >::type a_gamma_off(a_gamma_offSEXP);
    Rcpp::traits::input_parameter< double >::type b_gamma_off(b_gamma_offSEXP);
    rcpp_result_gen = Rcpp::wrap(BayDuBiG_mcmc(Y, gene_group_list, XWX, X_coord, Y_coord, weights, iter, burn, a_rho, b_rho, a_tau, b_tau, a_gamma, b_gamma, a_sigma, b_sigma, informative_gamma, a_gamma_on, b_gamma_on, a_gamma_off, b_gamma_off));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BayDuBiG_BayDuBiG_mcmc", (DL_FUNC) &_BayDuBiG_BayDuBiG_mcmc, 21},
    {NULL, NULL, 0}
};

RcppExport void R_init_BayDuBiG(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
