// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// run_mcmc
Rcpp::List run_mcmc(const arma::mat& Y, int n, int p, const arma::rowvec& gene_groups, const arma::mat& Z, const arma::sp_mat& weights, int iter, int burn, double a_rho, double b_rho, double a_tau, double b_tau, double a_gamma, double b_gamma, double a_sigma, double b_sigma, const std::vector<std::vector<double>>& precomputedTraces, int order, int m);
RcppExport SEXP _Baydubig_run_mcmc(SEXP YSEXP, SEXP nSEXP, SEXP pSEXP, SEXP gene_groupsSEXP, SEXP ZSEXP, SEXP weightsSEXP, SEXP iterSEXP, SEXP burnSEXP, SEXP a_rhoSEXP, SEXP b_rhoSEXP, SEXP a_tauSEXP, SEXP b_tauSEXP, SEXP a_gammaSEXP, SEXP b_gammaSEXP, SEXP a_sigmaSEXP, SEXP b_sigmaSEXP, SEXP precomputedTracesSEXP, SEXP orderSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type gene_groups(gene_groupsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< int >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< double >::type a_rho(a_rhoSEXP);
    Rcpp::traits::input_parameter< double >::type b_rho(b_rhoSEXP);
    Rcpp::traits::input_parameter< double >::type a_tau(a_tauSEXP);
    Rcpp::traits::input_parameter< double >::type b_tau(b_tauSEXP);
    Rcpp::traits::input_parameter< double >::type a_gamma(a_gammaSEXP);
    Rcpp::traits::input_parameter< double >::type b_gamma(b_gammaSEXP);
    Rcpp::traits::input_parameter< double >::type a_sigma(a_sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type b_sigma(b_sigmaSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<double>>& >::type precomputedTraces(precomputedTracesSEXP);
    Rcpp::traits::input_parameter< int >::type order(orderSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(run_mcmc(Y, n, p, gene_groups, Z, weights, iter, burn, a_rho, b_rho, a_tau, b_tau, a_gamma, b_gamma, a_sigma, b_sigma, precomputedTraces, order, m));
    return rcpp_result_gen;
END_RCPP
}
// Baydubig_mcmc
Rcpp::List Baydubig_mcmc(const arma::mat& Y, const arma::rowvec& gene_groups, const arma::mat& XWX, const arma::vec& X_coord, const arma::vec& Y_coord, const arma::sp_mat& weights, int iter, int burn, double a_rho, double b_rho, double a_tau, double b_tau, double a_gamma, double b_gamma, double a_sigma, double b_sigma);
RcppExport SEXP _Baydubig_Baydubig_mcmc(SEXP YSEXP, SEXP gene_groupsSEXP, SEXP XWXSEXP, SEXP X_coordSEXP, SEXP Y_coordSEXP, SEXP weightsSEXP, SEXP iterSEXP, SEXP burnSEXP, SEXP a_rhoSEXP, SEXP b_rhoSEXP, SEXP a_tauSEXP, SEXP b_tauSEXP, SEXP a_gammaSEXP, SEXP b_gammaSEXP, SEXP a_sigmaSEXP, SEXP b_sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type gene_groups(gene_groupsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type XWX(XWXSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type X_coord(X_coordSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y_coord(Y_coordSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< int >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< double >::type a_rho(a_rhoSEXP);
    Rcpp::traits::input_parameter< double >::type b_rho(b_rhoSEXP);
    Rcpp::traits::input_parameter< double >::type a_tau(a_tauSEXP);
    Rcpp::traits::input_parameter< double >::type b_tau(b_tauSEXP);
    Rcpp::traits::input_parameter< double >::type a_gamma(a_gammaSEXP);
    Rcpp::traits::input_parameter< double >::type b_gamma(b_gammaSEXP);
    Rcpp::traits::input_parameter< double >::type a_sigma(a_sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type b_sigma(b_sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(Baydubig_mcmc(Y, gene_groups, XWX, X_coord, Y_coord, weights, iter, burn, a_rho, b_rho, a_tau, b_tau, a_gamma, b_gamma, a_sigma, b_sigma));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Baydubig_run_mcmc", (DL_FUNC) &_Baydubig_run_mcmc, 19},
    {"_Baydubig_Baydubig_mcmc", (DL_FUNC) &_Baydubig_Baydubig_mcmc, 16},
    {NULL, NULL, 0}
};

RcppExport void R_init_Baydubig(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
