# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_mcmc <- function(Y, n, p, gene_groups, Z, weights, iter, burn, a_rho, b_rho, a_tau, b_tau, a_gamma, b_gamma, a_sigma, b_sigma, precomputedTraces, order, m) {
    .Call(`_Baydubig_run_mcmc`, Y, n, p, gene_groups, Z, weights, iter, burn, a_rho, b_rho, a_tau, b_tau, a_gamma, b_gamma, a_sigma, b_sigma, precomputedTraces, order, m)
}

Baydubig_mcmc <- function(Y, gene_groups, XWX, X_coord, Y_coord, weights, iter, burn, a_rho = 1.00, b_rho = 1.00, a_tau = 1, b_tau = 1, a_gamma = 1, b_gamma = 1, a_sigma = 0.01, b_sigma = 0.01) {
    .Call(`_Baydubig_Baydubig_mcmc`, Y, gene_groups, XWX, X_coord, Y_coord, weights, iter, burn, a_rho, b_rho, a_tau, b_tau, a_gamma, b_gamma, a_sigma, b_sigma)
}

