# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BayDuBiG_mcmc <- function(Y, gene_group_list, XWX, X_coord, Y_coord, weights, iter, burn, a_rho = 1.00, b_rho = 1.00, a_tau = 1, b_tau = 1, a_gamma = 1, b_gamma = 1, a_sigma = 0.01, b_sigma = 0.01, informative_gamma = FALSE, a_gamma_on = 10.0, b_gamma_on = 1.0, a_gamma_off = 1.0, b_gamma_off = 10.0) {
    .Call(`_BayDuBiG_BayDuBiG_mcmc`, Y, gene_group_list, XWX, X_coord, Y_coord, weights, iter, burn, a_rho, b_rho, a_tau, b_tau, a_gamma, b_gamma, a_sigma, b_sigma, informative_gamma, a_gamma_on, b_gamma_on, a_gamma_off, b_gamma_off)
}

